/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.Registeration_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class AssignSalaryForm extends javax.swing.JPanel {

    /**
     * Creates new form AssignSalaryForm
     */
    private RMS rms = null;

    public AssignSalaryForm(RMS rms) {
        this.rms = rms;
        initComponents();
    }

    private boolean checkValidation() {
        if (e_id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(AssignSalaryForm.this, "Enter Id");
            e_id.grabFocus();
            return false;
        } else if (salary.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(AssignSalaryForm.this, "Enter Salary");
            salary.grabFocus();
            return false;
        }
        return true;
    }
    
    private void reSet(){
     e_id.setText(null);
     salary.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        e_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assign Salary");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 46, 313, 92));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 240, -1, -1));

        e_id.setBackground(new java.awt.Color(255, 204, 204));
        e_id.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        e_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_idActionPerformed(evt);
            }
        });
        add(e_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 240, 134, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salary");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 292, -1, -1));

        salary.setBackground(new java.awt.Color(255, 204, 204));
        salary.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 289, 134, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee_ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 243, -1, -1));

        submitBtn.setBackground(new java.awt.Color(255, 204, 204));
        submitBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 349, -1, 42));

        clearBtn.setBackground(new java.awt.Color(255, 204, 204));
        clearBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 349, 101, 42));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 360, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, 110));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 90, 440));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 90, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 450, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void e_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_idActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
         if(checkValidation()){
            int id = Integer.parseInt(e_id.getText());
            float sal = Float.parseFloat(salary.getText());
            Registeration_DAO.updateSalary(id, sal);
        }
            reSet();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        reSet();
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField e_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField salary;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
