/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import app_classes.Ingredients;
import dao.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class IngredientsForm extends javax.swing.JPanel {

    /**
     * Creates new form IngredientsForm
     */
    private RMS rms =null;
    DefaultTableModel model;

    public IngredientsForm(RMS rms) {
        this.rms = rms;
        initComponents();
        model = (DefaultTableModel)ingredientTbl.getModel();
        load();
    }

    private boolean checkValidation() {
        if (ingredientName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(IngredientsForm.this, "Enter Name");
            ingredientName.grabFocus();
            return false;
        } else if (ingredientQty.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(IngredientsForm.this, "Enter Quantity");
            ingredientName.grabFocus();
            return false;
        }
        return true;
    }
    
    private void addRow(int id, String name, float qty, String decs) {
        model.insertRow(ingredientTbl.getRowCount(), new Object[]{id, name, qty, decs});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ingredientId = new javax.swing.JTextField();
        ingredientName = new javax.swing.JTextField();
        ingredientQty = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingDesc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ingredientTbl = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        updateBtn2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 710));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingredients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 29, -1, 63));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingredient Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingredient quantity");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingredient ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 266, -1, -1));

        ingredientId.setBackground(new java.awt.Color(255, 204, 204));
        ingredientId.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ingredientId.setEnabled(false);
        add(ingredientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, -1));

        ingredientName.setBackground(new java.awt.Color(255, 204, 204));
        ingredientName.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ingredientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientNameActionPerformed(evt);
            }
        });
        add(ingredientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 180, -1));

        ingredientQty.setBackground(new java.awt.Color(255, 204, 204));
        ingredientQty.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ingredientQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientQtyActionPerformed(evt);
            }
        });
        add(ingredientQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, -1));

        addBtn.setBackground(new java.awt.Color(255, 204, 204));
        addBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 88, 40));

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 89, 40));

        ingDesc.setBackground(new java.awt.Color(255, 204, 204));
        ingDesc.setColumns(20);
        ingDesc.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        ingDesc.setRows(5);
        jScrollPane1.setViewportView(ingDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 104));

        ingredientTbl.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N
        ingredientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingredient_Id", "Ingredient_Name", "Ingredient_Qty", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ingredientTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredientTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ingredientTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 760, 230));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 110, 440));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 510, 270));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/2.jpeg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 290, 270));

        updateBtn.setBackground(new java.awt.Color(255, 204, 204));
        updateBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 40));

        updateBtn2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        updateBtn2.setText("UPDATE");
        add(updateBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void ingredientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientNameActionPerformed

    private void ingredientQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientQtyActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (checkValidation()) {
            String ingName = ingredientName.getText();
            int ingQty = Integer.parseInt(ingredientQty.getText());
            String desc = ingDesc.getText();
            boolean flag = Ingredient_DAO.add(new Ingredients(ingName, ingQty, desc));
            if (flag) {
                JOptionPane.showMessageDialog(IngredientsForm.this, "...Ingredient is added...");
                load();
            } else {
                JOptionPane.showMessageDialog(IngredientsForm.this, "something went wrong...");
            }
            reSet();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int i = ingredientTbl.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(IngredientsForm.this, "Select any Row");
        } else {
            int id = Integer.parseInt(model.getValueAt(i, 0).toString());
            Ingredient_DAO.deleteRow(id);
            load();
            reSet();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ingredientTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredientTblMouseClicked
        // TODO add your handling code here:
        reSet();
        int i = ingredientTbl.getSelectedRow();
        if (i != -1) {
            ingredientId.setText(model.getValueAt(i, 0).toString());
            ingredientName.setText(model.getValueAt(i, 1).toString());
            ingredientQty.setText(model.getValueAt(i, 2).toString());
            ingDesc.setText(model.getValueAt(i, 3).toString());
        } else {
            JOptionPane.showMessageDialog(IngredientsForm.this, "Select any Row");
        }
    }//GEN-LAST:event_ingredientTblMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int i = ingredientTbl.getSelectedRow();
        if (i != -1 && checkValidation() && !(ingredientId.getText().trim().isEmpty())) {
            int id = Integer.parseInt(ingredientId.getText());
            String name = ingredientName.getText();
            int qty = (int)(Float.parseFloat(ingredientQty.getText()));
            String desc = ingDesc.getText();
            Ingredient_DAO.update(id, name, qty, desc);
            load();
            reSet();
        } else {
            JOptionPane.showMessageDialog(IngredientsForm.this, "Select Row to update");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        ingredientTbl.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void reSet() {
        ingredientName.setText(null);
        ingredientQty.setText(null);
        ingDesc.setText(null);
        ingredientId.setText(null);
    }
    
    private void load() {
        List<Ingredients> list = Ingredient_DAO.getAll();
        model.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Ingredients ingredient = list.get(i);
            int id = ingredient.getIng_id();
            String name = ingredient.getName();
            int qty = ingredient.getQty();
            String desc = ingredient.getDescription();
            addRow(id, name, qty, desc);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea ingDesc;
    private javax.swing.JTextField ingredientId;
    private javax.swing.JTextField ingredientName;
    private javax.swing.JTextField ingredientQty;
    private javax.swing.JTable ingredientTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateBtn2;
    // End of variables declaration//GEN-END:variables
}
