/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import app_classes.MealIngredients;
import app_classes.Meals;
import dao.MealsDAO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class MealForm extends javax.swing.JPanel {

    /**
     * Creates new form ItemsForm
     */
    private RMS rms = null;
    DefaultTableModel model;
    private String imagePath = null;
    private Meals m =null;
    
    public MealForm(RMS rms) {
        this.rms=rms;
        initComponents();
        model = (DefaultTableModel) mealsTbl.getModel();
        mealsTbl.removeColumn(mealsTbl.getColumnModel().getColumn(3));
        load();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private boolean checkValidation(){
        if(mealName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(MealForm.this, "Enter MEal Name");
            mealName.grabFocus();
            return false;
        }else if(mealCost.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(MealForm.this, "Enter Meal Cost");
            mealCost.grabFocus();
            return false;
        }
        return true;
    }
    private void loadImage(String path) {
        if (path != null && !path.trim().equalsIgnoreCase("null") && path.trim().length() > 0) {
            try {
                BufferedImage myPicture = ImageIO.read(new File(path));
                imageLabel.setIcon(new ImageIcon(myPicture.getScaledInstance(170,170, 170)));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private void load() {
        List<Meals> list = MealsDAO.getAll();
        model.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Meals item = list.get(i);
            int id = item.getM_id();
            String name = item.getName();
            float price = item.getPrice();
            String url = item.getImage();
            addRow(id, name,price,url);
        }
    }
    
    private void addRow(int id, String name,float price,String url) {
        model.insertRow(mealsTbl.getRowCount(), new Object[]{id, name,price,url});
    }
    
    private void reSetField() {
        mealCost.setText(null);
        mealId.setText(null);
        mealName.setText(null);
        imageLabel.setIcon(null);
        imagePath = null;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mealId = new javax.swing.JTextField();
        mealName = new javax.swing.JTextField();
        mealCost = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        imageBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealsTbl = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddIngredients = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 38, -1, 35));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Meal ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Meal Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 174, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Meal Cost");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 229, -1, -1));

        mealId.setBackground(new java.awt.Color(255, 204, 204));
        mealId.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        mealId.setEnabled(false);
        mealId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealIdActionPerformed(evt);
            }
        });
        add(mealId, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 117, 154, 35));

        mealName.setBackground(new java.awt.Color(255, 204, 204));
        mealName.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        mealName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealNameActionPerformed(evt);
            }
        });
        add(mealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 170, 154, 37));

        mealCost.setBackground(new java.awt.Color(255, 204, 204));
        mealCost.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        add(mealCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 225, 154, 37));

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 117, 149, 125));

        imageBtn.setBackground(new java.awt.Color(255, 204, 204));
        imageBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        imageBtn.setText("Choose Image");
        imageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageBtnActionPerformed(evt);
            }
        });
        add(imageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 260, -1, -1));

        addBtn.setBackground(new java.awt.Color(255, 204, 204));
        addBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.setPreferredSize(new java.awt.Dimension(90, 34));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 338, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.setPreferredSize(new java.awt.Dimension(90, 34));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 338, -1, -1));

        updateBtn.setBackground(new java.awt.Color(255, 204, 204));
        updateBtn.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.setPreferredSize(new java.awt.Dimension(90, 34));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 338, -1, -1));

        mealsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meal_ID", "Meal Name", "Meal_Price", "image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mealsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealsTblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mealsTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(mealsTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 710, 350));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 460, 310));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/2.jpeg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 360, 310));

        btnAddIngredients.setBackground(new java.awt.Color(255, 204, 204));
        btnAddIngredients.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnAddIngredients.setText("ADD INGREDIENTS");
        btnAddIngredients.setPreferredSize(new java.awt.Dimension(90, 34));
        btnAddIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIngredientsActionPerformed(evt);
            }
        });
        add(btnAddIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 170, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 140, 440));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 680, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void mealIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealIdActionPerformed

    private void mealNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealNameActionPerformed

    private void mealsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsTblMouseClicked
        // TODO add your handling code here:
        reSetField();
        int i =mealsTbl.getSelectedRow();
        if (i != -1) {
            mealId.setText(model.getValueAt(i, 0).toString());
            mealName.setText(model.getValueAt(i, 1).toString());
            mealCost.setText(model.getValueAt(i, 2).toString());
            loadImage(model.getValueAt(i, 3).toString());
        } else {
            JOptionPane.showMessageDialog(MealForm.this, "Select any Row");
        }
    }//GEN-LAST:event_mealsTblMouseClicked

    private void mealsTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealsTblMousePressed
        // TODO add your handling code here:
        int i = mealsTbl.getSelectedRow();
        if(evt.getClickCount() == 2 && i != -1){
            this.rms.addComponent(new MealIngredientsForm(this.rms,this.m,0));
        }
    }//GEN-LAST:event_mealsTblMousePressed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(checkValidation()){
            String umealName = mealName.getText();
            int umealCost = Integer.parseInt(mealCost.getText());
            Meals meal = new Meals(umealName,umealCost,imagePath);
            
            boolean check = MealsDAO.ADD(meal);
            
            reSetField();
            if (check) {
                JOptionPane.showMessageDialog(MealForm.this, "Meal added successfully..");
                load();
            } else {
                JOptionPane.showMessageDialog(MealForm.this, "Error!");
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void imageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("."));
        int result = fileChooser.showOpenDialog(this.rms);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            imagePath = selectedFile.getAbsolutePath();
            loadImage(selectedFile.getAbsolutePath());
        }
        
    }//GEN-LAST:event_imageBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         int i = mealsTbl.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(MealForm.this, "Select any Row");
        } else {
            int id = Integer.parseInt(model.getValueAt(i, 0).toString());
            MealsDAO.deleteRow(id);
            load();
            reSetField();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int i = mealsTbl.getSelectedRow();
        if (i != -1 && checkValidation() && !(mealId.getText().trim().isEmpty())) {
            int id = Integer.parseInt(mealId.getText());
            String name = mealName.getText();
            float cost = Float.parseFloat(mealCost.getText());
            String url = imagePath;
            MealsDAO.update(id,name,cost,url);
            load();
            reSetField();
        } else {
            JOptionPane.showMessageDialog(MealForm.this, "Select Row to update");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void btnAddIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIngredientsActionPerformed
        // TODO add your handling code here:
        int i = mealsTbl.getSelectedRow();
        if (i != -1 && checkValidation() && !(mealId.getText().trim().isEmpty())) {
            int id = Integer.parseInt(mealId.getText());
            String name = mealName.getText();
            float cost = Float.parseFloat(mealCost.getText());
            String url = imagePath;
            m = new Meals(id,name,cost,url);
            this.rms.addComponent(new MealIngredientsForm(this.rms,this.m));
         } else {
            JOptionPane.showMessageDialog(MealForm.this, "Select Meal");
        }
    }//GEN-LAST:event_btnAddIngredientsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnAddIngredients;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton imageBtn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mealCost;
    private javax.swing.JTextField mealId;
    private javax.swing.JTextField mealName;
    private javax.swing.JTable mealsTbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
