/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import app_classes.Order;
import app_classes.OrderDetails;
import dao.*;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class OrdersForm extends javax.swing.JPanel {

    /**
     * Creates new form OrdersForm
     */
    private RMS rms = null;
    DefaultTableModel model;
    
    public OrdersForm(RMS rms) {
        this.rms = rms;
        initComponents();
        model = (DefaultTableModel) ordersTbl.getModel();
        ordersTbl.removeColumn(ordersTbl.getColumnModel().getColumn(4));
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void load() {
        List<Order> list = Order_DAO.getAll();
        model.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Order order = list.get(i);
            String o_id = order.getO_id();
            String cName = Customer_DAO.getPerson(order.getC_id()).getName();
            String eName = Customer_DAO.getPerson(order.getE_id()).getName();
            String date = ""+order.getOrderDate();
            float price= order.getTotalPrice();
            addRow(cName,eName,date,price,o_id);

        }

    }

    private void addRow(String cName,String eName,String date,float price,String o_id) {
        model.insertRow(ordersTbl.getRowCount(), new Object[]{cName,eName,date,price,o_id});
    }
    
    private void load_2(int id) {
        List<Order> list = Order_DAO.getAllByEmployee(id);
        if(list != null){
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                Order order = list.get(i);
                String o_id = order.getO_id();
                String cName = Customer_DAO.getPerson(order.getC_id()).getName();
                String eName = Customer_DAO.getPerson(order.getE_id()).getName();
                String date = "" + order.getOrderDate();
                float price = order.getTotalPrice();
                addRow(cName, eName, date, price, o_id);

            }
        }else{
            JOptionPane.showMessageDialog(OrdersForm.this, "Invalid id");
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orders");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 106, -1, -1));

        ID.setBackground(new java.awt.Color(255, 204, 204));
        ID.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 103, 137, -1));

        searchBtn.setBackground(new java.awt.Color(255, 204, 204));
        searchBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 102, -1, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 102, -1, -1));

        ordersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Employee Name", "Order Date", "Total Price", "order_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ordersTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ordersTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 142, 689, 507));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 36, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 460));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 510, 270));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 290, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int i = ordersTbl.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(OrdersForm.this, "Select any Row");
        } else {
            String id = (model.getValueAt(i, 4).toString());
            Order_DAO.deleteRow(id);
            load();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if (ID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(OrdersForm.this, "Enter Id");
        }else{
            load_2(Integer.parseInt(ID.getText()));
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void ordersTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersTblMousePressed
        // TODO add your handling code here:
        int i = ordersTbl.getSelectedRow();
        if(evt.getClickCount() == 2 && i != -1){
            this.rms.addComponent(new OrderDetailsForm(this.rms,model.getValueAt(i, 4).toString()));
        }
    }//GEN-LAST:event_ordersTblMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordersTbl;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
