/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import app_classes.OrderDetails;
import app_classes.Receipt;
import dao.MealsDAO;
import dao.OrderDetails_DAO;
import javax.swing.DefaultListModel;

/**
 *
 * @author dell
 */
public class OrderDetailsForm extends javax.swing.JPanel {

    /**
     * Creates new form OrderDetails
     */
    private RMS rms= null;
    private String order_id;
    private DefaultListModel listModel1;
     
    public OrderDetailsForm(RMS rms,String order_id) {
        this.rms = rms;
        this.order_id = order_id;
        initComponents();
        load(order_id);
        
    }
    
    private void load(String order_id){
        Receipt rec = OrderDetails_DAO.getReceipt(order_id);
        customerName.setText(rec.getcName());
        employeeName.setText(rec.geteName());
        date.setText(""+rec.getDate());
        totalPrice.setText(""+rec.getTotalPrice());
        DefaultListModel <String> listModel1 = new DefaultListModel();
        for(OrderDetails meal: rec.getMeals()){
            String name = MealsDAO.getMealName(meal.getM_id());
            listModel1.addElement(name);
        }
        meals.setModel(listModel1);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        employeeName = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        totalPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        meals = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 133, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 182, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Meals");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        customerName.setBackground(new java.awt.Color(255, 204, 204));
        customerName.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        customerName.setEnabled(false);
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 130, 154, -1));

        employeeName.setBackground(new java.awt.Color(255, 204, 204));
        employeeName.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        employeeName.setEnabled(false);
        employeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameActionPerformed(evt);
            }
        });
        add(employeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 179, 154, -1));

        date.setBackground(new java.awt.Color(255, 204, 204));
        date.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        date.setEnabled(false);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 154, -1));

        totalPrice.setBackground(new java.awt.Color(255, 204, 204));
        totalPrice.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        totalPrice.setEnabled(false);
        add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 154, -1));

        meals.setBackground(new java.awt.Color(255, 204, 204));
        meals.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        meals.setEnabled(false);
        jScrollPane1.setViewportView(meals);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 240, 150, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/4.jpg"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 590, 270));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 210, 340));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/1.jpg"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 380, 320));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/2.jpeg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 360, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void employeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField date;
    private javax.swing.JTextField employeeName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> meals;
    private javax.swing.JTextField totalPrice;
    // End of variables declaration//GEN-END:variables
}
