CREATE DATABASE RESTURANT_DB;

CREATE TABLE PERSON(
P_ID INT IDENTITY(1,1),
P_NAME VARCHAR(50),
GENDER CHAR(1),
ADDRESS VARCHAR(50),
PHONE_NUMBER VARCHAR(20),
EMAIL VARCHAR(20),

PRIMARY KEY(P_ID)
)

CREATE TABLE EMPLOYEE(
P_ID INT,
TOTAL_ORDERS_COUNT INT,
SALARY FLOAT,
PASSWORD VARCHAR(30),
BONUS FLOAT,

PRIMARY KEY (P_ID),
FOREIGN KEY(P_ID)  REFERENCES PERSON(P_ID) 
ON DELETE CASCADE
ON UPDATE CASCADE
)

CREATE TABLE CUSTOMER(
P_ID INT,

PRIMARY KEY (P_ID),
FOREIGN KEY(P_ID) REFERENCES PERSON(P_ID)
ON DELETE CASCADE
ON UPDATE CASCADE  
)

CREATE TABLE MANAGER(
P_ID INT,
SALARY FLOAT,
PASSWORD VARCHAR(30),

PRIMARY KEY (P_ID),
FOREIGN KEY(P_ID) REFERENCES PERSON(P_ID)
ON DELETE CASCADE
ON UPDATE CASCADE  
)


CREATE TABLE ORDERS(
OREDER_ID INT IDENTITY(1,1),
C_ID INT,
E_ID INT,
ORDER_DATE DATETIME,
TOTAL_PRICE FLOAT,

PRIMARY KEY(OREDER_ID),
FOREIGN KEY (C_ID) REFERENCES CUSTOMER (P_ID),
FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (P_ID)

--ON DELETE CASCADE
--ON UPDATE CASCADE,  

--cascade not working it can be solved via this method by defining triggers
--https://www.mssqltips.com/sqlservertip/1804/using-instead-of-triggers-in-sql-server-for-dml-operations/
 
)

CREATE TABLE MEALS(
MEAL_ID INT IDENTITY(1,1),
NAME VARCHAR(30),
PRICE FLOAT,
IMAGE VARCHAR(50), 
PRIMARY KEY(MEAL_ID),
)

CREATE TABLE ORDER_DETAILS(
OREDER_ID INT,
MEAL_ID INT,
QUANTITY INT,

FOREIGN KEY (OREDER_ID) REFERENCES ORDERS (OREDER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,  
FOREIGN KEY (MEAL_ID) REFERENCES MEALS (MEAL_ID)
ON DELETE CASCADE
ON UPDATE CASCADE 
)

CREATE TABLE INGREDIENTS(
ING_ID INT IDENTITY(1,1),
NAME VARCHAR(30),
QTY INT,
DESCRIPTION VARCHAR(30),
IMAGE VARCHAR(50),

PRIMARY KEY (ING_ID)
)

CREATE TABLE MEAL_INGREDIENTS(
ING_ID INT,
MEAL_ID INT,
QUNATITY INT,

FOREIGN KEY (ING_ID) REFERENCES INGREDIENTS (ING_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,  
FOREIGN KEY (MEAL_ID) REFERENCES MEALS (MEAL_ID)
ON DELETE CASCADE
ON UPDATE CASCADE  
)




